### ISSUE TITLE
localePath?

### ISSUE THREAD

**Issue by terion-name** [intlify/nuxt3#21]
Does this support `localePath` and other helpers from `nuxt-i18n`?

**Comment by f3ltron** [comment]
Would like to know also

**Comment by gvankruijsdijk** [comment]
Does the package even generate te localePath routes, or is there any option to do so?

**Comment by lacorde** [comment]
@gvankruijsdijk I have no idea and I am very interested to find out !
How to replace setLocale and localePath in a Nuxt 3 project ?

**Comment by terion-name** [comment]
it is already obvious that this package has no integration with router, rendering it literally useless for real life. 

and this, alongside with developers ignoring issues, is just awful. currently I see no way to make a proper multilang app with nuxt3 (

**Comment by terion-name** [comment]
@kazupon please, take a look

**Comment by kazupon** [comment]
>It also has the purpose of finding issues on the vue-i18n-next so that @nuxtjs/i18n can support Nuxt3.

As mentioned in the README, this project is aimed at providing @nuxtjs/i18n with nuxt bridge / nuxt 3 support.

And I'm sharing information in GitHub discussions on `@nuxtjs/i18n` to support its development status.
https://github.com/nuxt-community/i18n-module/discussions/1334

I am not a full-time OSS developer, but I am working on development in my free time every day.
For this reason, I would love to comment on everything if I had the time, but unfortunately, that is not possible.

I have a family, and I spend a lot of time working on development.
I hope you would be able to understand my situation.

Thanks.
