### ISSUE TITLE
You are running the esm-bundler build of vue-i18n

### ISSUE THREAD

**Issue by Droutin** [intlify/nuxt3#42]
How to get rid of this error?
`You are running the esm-bundler build of vue-i18n. It is recommended to configure your bundler to explicitly replace feature flag globals with boolean literals to get proper tree-shaking in the final bundle.`

**Comment by jojomatik** [comment]
I'm seeing this as well, but only during development mode. The production build does seem to work fine. 

Also I wanted to add that the message is received in the browser console.

**Comment by anburocky3** [comment]
I'm also seeing this error on the console.warn
