### ISSUE TITLE
Error:  Duplicate export 'default' (Note that you need plugins to import files that are not JavaScript)

### ISSUE THREAD

**Issue by jojomatik** [intlify/nuxt3#47]
My nuxt3 templates fails to build with a new nuxt version:

**PR run:** https://github.com/jojomatik/nuxt-3-base/runs/5617517319?check_suite_focus=true

```
[log] Nuxt CLI v3.0.0-2746048[9](https://github.com/jojomatik/nuxt-3-base/runs/5617517319?check_suite_focus=true#step:7:9).53fbca7
[warn] Error when using sourcemap for reporting an error: Can't resolve original location of error.
Error:  Duplicate export 'default' (Note that you need plugins to import files that are not JavaScript)
file: virtual:/home/runner/work/nuxt-3-base/nuxt-3-base/.nuxt/intlify.vuei18n.options.mjs:3:7
1: 
2: export default () => Promise.resolve({"locale":"en","fallbackLocale":"en"})
3: export default () => Promise.resolve({"locale":"en","fallbackLocale":"en"})
          ^
Error:  Duplicate export 'default' (Note that you need plugins to import files that are not JavaScript)
  at error (node_modules/rollup/dist/shared/rollup.js:198:30)
  at Module.error (node_modules/rollup/dist/shared/rollup.js:[12](https://github.com/jojomatik/nuxt-3-base/runs/5617517319?check_suite_focus=true#step:7:12)477:[16](https://github.com/jojomatik/nuxt-3-base/runs/5617517319?check_suite_focus=true#step:7:16))
  at Module.tryParse (node_modules/rollup/dist/shared/rollup.js:12853:25)
  at Module.setSource (node_modules/rollup/dist/shared/rollup.js:12756:24)
  at ModuleLoader.addModuleSource (node_modules/rollup/dist/shared/rollup.js:222[20](https://github.com/jojomatik/nuxt-3-base/runs/5617517319?check_suite_focus=true#step:7:20):20)
Error: Process completed with exit code 1.
```

**Works fine with previous version of nuxt3:** https://github.com/jojomatik/nuxt-3-base/runs/5617504148?check_suite_focus=true

**Diff:** https://github.com/jojomatik/nuxt-3-base/pull/17/files

I've also tried to switch to `@nuxtjs/i18n-edge` as you recommended that in #44, but I could not get it working. I think it's propably a small change to switch the library, but I didn't find enought documentation unfortunately.

**Comment by leo91000** [comment]
I had the same problem and managed to fix it by putting dependency override (I use pnpm) :

package.json
```json
  "pnpm": {
    "overrides": {
      "@nuxt/kit": "npm:@nuxt/kit-edge@latest",
      "@nuxt/kit-edge": "latest"
    }
  }
```

If you don't use pnpm maybe a lock file resfresh is enough

**Comment by jojomatik** [comment]
> If you don't use pnpm maybe a lock file resfresh is enough

Thanks @leo91000, recreating the lockfile after deleting `/node_modules` fixes the issue for me.

Do you have any insights why this happened? Is this an issue of how this project handles its dependencies or is npm just not working that well with these "weird" nuxt3 beta version numbers and all other related beta/ alpha/ rc versions?

**Comment by leo91000** [comment]
I have no idea why this happens . Probably the fact that nuxt 3 is not released yet so it makes breaking changes to it's packages (in this case `@nuxt/kit`). Then you have two incompatible version because updating nuxt3 is not enough.

**Comment by jojomatik** [comment]
I believe this issue can be closed. Recreating the lockfile worked and I believe the bug does not occur with the newer versions of nuxt.
